[package]
name = "libversion"
description = "Advanced version string comparison algorithm"
version = "0.2.0"
authors = ["Dmitry Marakasov <amdmi3@amdmi3.ru>"]
repository = "https://github.com/repology/libversion-rs"
readme = "README.md"
categories = ["algorithms", "version", "comparison"]
license = "MIT"
edition = "2021"

[[bench]]
name = "comparison"
harness = false

[dependencies]
bitflags = "2.6.0"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
regex = { version = "1.10.6", default-features = false, features = ["std"] }
