name: CI
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { rust: nightly }
          - { rust: stable }
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
#        if: ${{ contains(matrix.features, 'coverage') }}
#        uses: codecov/codecov-action@v3
#        with:
#          fail_ci_if_error: true
#          gcov: true
