name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 1"
jobs:
  test:
    env:
      RUSTFLAGS: -Dwarnings
    strategy:
      matrix:
        include:
          - { name: "Rust 1.88",    rust: "1.88" }
          - { name: "Rust stable",  rust: stable }
          - { name: "Rust nightly", rust: nightly-2026-04-21 }
      fail-fast: false
    runs-on: ubuntu-latest
    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt,clippy
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/master' }}
          cache-bin: "false"
      - name: Format check
        run: cargo fmt --check
      - name: Clippy check
        run: cargo clippy --all-targets
      - name: Test
        run: cargo test ${{ matrix.cargo_args }}
